name: carbon_voice_console
description: "A Flutter admin console application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.1.0
  
  # Routing
  go_router: ^14.6.2
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  meta: ^1.13.0
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Networking
  dio: ^5.7.0
  http: ^1.2.0

  # OAuth
  oauth2: ^2.0.2
  crypto: ^3.0.5

  # JSON Serialization
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  logger: ^2.6.2
  uuid: ^4.5.1

  # File system access
  path_provider: ^2.1.1
  path: ^1.9.0

  # Platform-specific implementations
  universal_html: ^2.2.4

  # Audio Playback
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/carbon-voice-logo.png




