name: carbon_voice_console
description: "A Flutter admin console application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Routing
  go_router: ^14.6.2
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Networking
  dio: ^5.7.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true




